CREATE DEFINER=`root`@`localhost` PROCEDURE `RATINGS`()
BEGIN

SELECT S.SUPP_ID , S.SUPP_NAME,AVG(R.RAT_RATSTARS) AS RATING ,CASE
WHEN AVG (R.RAT_RATSTARS) =5 THEN "EXCELLENT SERVICE"
WHEN AVG (R.RAT_RATSTARS) < 5 AND AVG(R.RAT_RATSTARS) >= 4 THEN "GOOD SERVICE"
WHEN AVG (R.RAT_RATSTARS) < 4 AND AVG (R.RAT_RATSTARS) >= 2  THEN "AVERAGE SERVICE"
ELSE "POOR SERVICE"
END AS TYPE_OF_SERVICE 
FROM ORDERS O, RATING R ,SUPPLIER_PRICING SP,SUPPLIER S WHERE R.ORD_ID = O.ORD_ID AND SP.PRICING_ID = O.PRICING_ID AND S.SUPP_ID = SP.SUPP_ID 
GROUP BY S.SUPP_ID , S.SUPP_NAME ;


END